services:
  #  admin:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    ports:
  #      - "8000:8000"
  #    environment:
  #      LARAVEL_DB_HOST: postgres
  #    volumes:
  #      - .:/var/www/html
  #    depends_on:
  #      - db

  #  my:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    ports:
  #      - "8200:8000"
  #    volumes:
  #      - .:/var/www/html
  #    depends_on:
  #      - db

  #  manage:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    ports:
  #      - "8100:8000"
  #    environment:
  #      LARAVEL_DB_HOST: postgres
  #    volumes:
  #      - .:/var/www/html
  #    depends_on:
  #      - db

  # PostgreSQL Database
  db:
    image: postgres:17.6-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scf
    ports:
      - "3335:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg_logs:/var/lib/postgresql/data/log
      - ./docker/pg-config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    restart: always
#    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: username@username.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always

  # MongoDB Database
  mongo:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  # Mongo Express UI
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: username
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_SITE_COOKIESECRET: tools-mongo-web077348dd1cfd15d2
      ME_CONFIG_SITE_SESSIONSECRET: tools-mongo-web39dd5a11d636c2ee
    ports:
      - "8081:8081"
    restart: always

  # Redis Cache
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  postgres-data:
  mongo-data:
  pgadmin-data:
  redis-data:

networks:
  default:
